POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
###
POST http://localhost:8080/file/compare/createInfo
Content-Type:  application/json

{
  "name":"原始文档.pdf",
  "merge_diff":1
}
###

GET  http://127.0.0.1:8080/file/compare/getToken

###

POST http://192.168.84.124:8080/file/compare/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file";filename="a.pdf"
Content-Type: application/json

< /Users/cong/Downloads/a.pdf
--WebAppBoundary--

###
GET http://192.168.84.124:8080/file/compare/compare
###

POST http://192.168.84.124:8080/file/compare/updateTask
Content-Type: application/json

{
  "compareId": ""
}

###

POST 192.168.84.124:8080/param/test
Content-Type: application/x-www-form-urlencoded

name=aaa
###
POST 192.168.84.124:8080/param/test?name=aaa
###